= Hibernate Streams Wrapper
Jakub Narloch <j.narloch@gmail.com>
:toc: left
:sectnums:

An Java 8 wrapper on top Hibernate Query API

Compatibility: Hibernate 4.3.x

== Introduction

Since Hibernate 4.x/5.x maintain still backward compatibility with Java 6/7
this small project has been introduced in order to bring the benefits of Java 8
streams, optional objects and new date API.

=== The wrapper

Using the extended API is straightforward, simply pass your SessionFactory instance to `Streams.wrap` method.

[source, java]
----

SessionFactory sessionFactory = ... // create your session factory in standard manner
StreamSessionFactory streamsFactory = Streams.wrap(sessionFactory);

----

The StreamSessionFactory wrapper overloads bunch of the existing methods and additionally defines new ones.

The modified API classes and their counterparts can be summarized in the table

[cols="2*", options="header"]
|===
| Hibernate OR/M | Wrapper

| SessionFactory | StreamSessionFactory
| Session | StreamSession
| StatelessSession | StreamStatelessSession
| SessionBuilder | StreamSessionBuilder
| StatelessSessionBuilder | StreamStatelessSessionBuilder
| Query | StreamQuery
| SQLQuery | StreamSQLQuery

|===


=== StreamSession
`StreamSession` now allows to retrieve optional entities by calling `getOptional()` method.

=== StreamQuery
The `StreamQuery` introduces fallowing methods:

* stream()
* parallelStream()
* getOptional()

=== LocalDate/LocalTime
Now the newly introduced Java 8 `LocalDate` and `LocalTime` can be used as query parameters through convenient set methods.

* setLocalDate(int position, LocalDate localDate)
* setLocalDate(String name, LocalDate localDate)
* setLocalTime(int position, LocalTime localTime)
* setLocalTime(String name, LocalTime localTime)

=== Typed Queries
The wrapper finally brings to the query API strongly typed queries making it convinient for operating on
list, streams and optional of concrete types instead of plain objects.

[source, java]
----

Optional<User> user = session.createTypedQuery("from User where id = :id", User.class)
                .setParameter("id", 1l)
                .stream()
                .findFirst();

----

Newly introduced methods includes:

* `createTypedQuery(String queryString, Class<T> clazz)`
* `getTypedNamedQuery(String queryName, Class<T> clazz)`
* `createTypedSQLQuery(String queryString, Class<T> clazz)`

=== Extended entity mapping
TBD